class AddHealthcare < ActiveRecord::Migration[5.1]
  def up
    Healthcare.create(id: 1, name: 'Aag')
    Healthcare.create(id: 2, name: 'Abertta')
    Healthcare.create(id: 3, name: 'Abet')
    Healthcare.create(id: 4, name: 'Aeronáutica')
    Healthcare.create(id: 5, name: 'Agros')
    Healthcare.create(id: 6, name: 'Allianz / Agf')
    Healthcare.create(id: 7, name: 'Amagis Saúde')
    Healthcare.create(id: 8, name: 'Amil / Amil Planos / Amil Medial')
    Healthcare.create(id: 9, name: 'Ammp')
    Healthcare.create(id: 10, name: 'Assefaz')
    Healthcare.create(id: 11, name: 'Assembléia / Prelegis')
    Healthcare.create(id: 12, name: 'Assistcard / Assistbrasil')
    Healthcare.create(id: 13, name: 'Bacen')
    Healthcare.create(id: 14, name: 'Bh – Trans')
    Healthcare.create(id: 15, name: 'Bradesco Saúde')
    Healthcare.create(id: 16, name: 'Caarf / Unafisco Mg')
    Healthcare.create(id: 17, name: 'Cabesp')
    Healthcare.create(id: 18, name: 'Camed')
    Healthcare.create(id: 19, name: 'Canadá Seguros')
    Healthcare.create(id: 20, name: 'Care Plus')
    Healthcare.create(id: 21, name: 'Carmen Sales')
    Healthcare.create(id: 22, name: 'Casembrapa')
    Healthcare.create(id: 23, name: 'Cassi')
    Healthcare.create(id: 24, name: 'Cef / Saúde Caixa')
    Healthcare.create(id: 25, name: 'Cemig Saúde / Forluz')
    Healthcare.create(id: 26, name: 'Cenibra')
    Healthcare.create(id: 27, name: 'Cnen')
    Healthcare.create(id: 28, name: 'Conab')
    Healthcare.create(id: 29, name: 'Copasa / Copass')
    Healthcare.create(id: 30, name: 'Coris Brasil ')
    Healthcare.create(id: 31, name: 'Cruzeiro')
    Healthcare.create(id: 32, name: 'Cvrd - Vale')
    Healthcare.create(id: 33, name: 'Desban')
    Healthcare.create(id: 34, name: 'Disbel')
    Healthcare.create(id: 35, name: 'Embratel / Pame / Claro / Telos')
    Healthcare.create(id: 36, name: 'Eurocenter')
    Healthcare.create(id: 37, name: 'Fiat Saúde')
    Healthcare.create(id: 38, name: 'Fsfx / Usisaúde ')
    Healthcare.create(id: 39, name: 'Fundação Libertas')
    Healthcare.create(id: 40, name: 'Fundação Saúde Itau')
    Healthcare.create(id: 41, name: 'Fundaffemg')
    Healthcare.create(id: 42, name: 'Fusex')
    Healthcare.create(id: 43, name: 'Gama ')
    Healthcare.create(id: 44, name: 'Golden Cross')
    Healthcare.create(id: 45, name: 'Good Life')
    Healthcare.create(id: 46, name: 'Imm')
    Healthcare.create(id: 47, name: 'Imn')
    Healthcare.create(id: 48, name: 'Infraero')
    Healthcare.create(id: 49, name: 'Interpartner ')
    Healthcare.create(id: 50, name: 'Intra Sul De Minas')
    Healthcare.create(id: 51, name: 'Iprem')
    Healthcare.create(id: 52, name: 'Irmãs Franciscanas')
    Healthcare.create(id: 53, name: 'Life Saúde')
    Healthcare.create(id: 54, name: 'Mapfre - Brasil Assistência')
    Healthcare.create(id: 55, name: 'Mapresaude')
    Healthcare.create(id: 56, name: 'Mater Dei ')
    Healthcare.create(id: 57, name: 'Mediservice')
    Healthcare.create(id: 58, name: 'Minas Brasil / Veritas Bpo')
    Healthcare.create(id: 59, name: 'Minas Tênis Clube')
    Healthcare.create(id: 60, name: 'Mondial ')
    Healthcare.create(id: 61, name: 'Monte Calvário')
    Healthcare.create(id: 62, name: 'Neocenter')
    Healthcare.create(id: 63, name: 'Notredame')
    Healthcare.create(id: 64, name: 'Omint')
    Healthcare.create(id: 65, name: 'Petrobrás Disbel')
    Healthcare.create(id: 66, name: 'Petrobrás Regap')
    Healthcare.create(id: 67, name: 'Plan Assiste')
    Healthcare.create(id: 68, name: 'Porto Seguro')
    Healthcare.create(id: 69, name: 'Postal Saúde/ Correios')
    Healthcare.create(id: 70, name: 'Pró-Social / Justiça ')
    Healthcare.create(id: 71, name: 'Proasa')
    Healthcare.create(id: 72, name: 'Promed')
    Healthcare.create(id: 73, name: 'Rmnsd')
    Healthcare.create(id: 74, name: 'Santo Inácio')
    Healthcare.create(id: 75, name: 'Saúde')
    Healthcare.create(id: 76, name: 'Seias ')
    Healthcare.create(id: 77, name: 'Serpram')
    Healthcare.create(id: 78, name: 'Serpro')
    Healthcare.create(id: 79, name: 'Sindifisco / Unaf.Saúde')
    Healthcare.create(id: 80, name: 'Sistema Paulista / Spa')
    Healthcare.create(id: 81, name: 'Sompo - Marítima')
    Healthcare.create(id: 82, name: 'Sos Assistance')
    Healthcare.create(id: 83, name: 'Sulamérica')
    Healthcare.create(id: 84, name: 'Travelece')
    Healthcare.create(id: 85, name: 'Unamgem')
    Healthcare.create(id: 86, name: 'Unimed Além Paraiba')
    Healthcare.create(id: 87, name: 'Unimed Alfenas')
    Healthcare.create(id: 88, name: 'Unimed Alto Paranaiba')
    Healthcare.create(id: 89, name: 'Unimed Alto São Francisco')
    Healthcare.create(id: 90, name: 'Unimed Andradas')
    Healthcare.create(id: 91, name: 'Unimed Araguari')
    Healthcare.create(id: 92, name: 'Unimed Araxá')
    Healthcare.create(id: 93, name: 'Unimed Barbacena')
    Healthcare.create(id: 94, name: 'Unimed BH')
    Healthcare.create(id: 95, name: 'Unimed Campo Belo- Cooperativa De Trabalho Médico')
    Healthcare.create(id: 96, name: 'Unimed Caratinga - Cooperativa De Trabalho Médico')
    Healthcare.create(id: 97, name: 'Unimed Cataguases Cooperativa De Trabalho Médico Ltda')
    Healthcare.create(id: 98, name: 'Unimed Centro-Oeste')
    Healthcare.create(id: 99, name: 'Unimed Circuito Das Aguas')
    Healthcare.create(id: 100, name: 'Unimed Conselheiro Lafaiete')
    Healthcare.create(id: 101, name: 'Unimed Divinopolis')
    Healthcare.create(id: 102, name: 'Unimed Frutal Cooperativa De Trabalho Médico')
    Healthcare.create(id: 103, name: 'Unimed Gerais De Minas')
    Healthcare.create(id: 104, name: 'Unimed Guaxupé')
    Healthcare.create(id: 105, name: 'Unimed Gv Coop Trabalho Medico Ltda')
    Healthcare.create(id: 106, name: 'Unimed Inconfidentes')
    Healthcare.create(id: 107, name: 'Unimed Itabira Cooperativa De Trabalho Medico')
    Healthcare.create(id: 108, name: 'Unimed Itajuba Cooperativa De Trabalho Medico')
    Healthcare.create(id: 109, name: 'Unimed Itaúna')
    Healthcare.create(id: 110, name: 'Unimed Ituiutaba')
    Healthcare.create(id: 111, name: 'Unimed João Monlevade')
    Healthcare.create(id: 112, name: 'Unimed Juiz De Fora Cooperativa De Trabalho Medico Ltda')
    Healthcare.create(id: 113, name: 'Unimed Lavras')
    Healthcare.create(id: 114, name: 'Unimed Leopldina')
    Healthcare.create(id: 115, name: 'Unimed Machado')
    Healthcare.create(id: 116, name: 'Unimed Muriaé Cooperativa De Trabalho Medico Ltda')
    Healthcare.create(id: 117, name: 'Unimed Noroeste De Minas')
    Healthcare.create(id: 118, name: 'Unimed Norte De Minas')
    Healthcare.create(id: 119, name: 'Unimed Patos De Minas Cooperativa Trabalho Médico')
    Healthcare.create(id: 120, name: 'Unimed Patrocínio')
    Healthcare.create(id: 121, name: 'Unimed Pocos De Caldas')
    Healthcare.create(id: 122, name: 'Unimed Pontal Do Triângulo')
    Healthcare.create(id: 123, name: 'Unimed Ponte Nova E Região')
    Healthcare.create(id: 124, name: 'Unimed São João Del Rei Cooperativa De Trabalho Medico')
    Healthcare.create(id: 125, name: 'Unimed São João Nepomuceno')
    Healthcare.create(id: 126, name: 'Unimed São Sebastião Do Paraíso')
    Healthcare.create(id: 127, name: 'Unimed Seguros')
    Healthcare.create(id: 128, name: 'Unimed Serras De Minas')
    Healthcare.create(id: 129, name: 'Unimed Sete Lagoas Cooperativa Trabalho Medico')
    Healthcare.create(id: 130, name: 'Unimed Sudoeste De Minas')
    Healthcare.create(id: 131, name: 'Unimed Três Corações Cooperativa De Trabalho Médico Ltda.')
    Healthcare.create(id: 132, name: 'Unimed Três Pontas - Cooperativa De Trabalho Médico')
    Healthcare.create(id: 133, name: 'Unimed Tres Vales')
    Healthcare.create(id: 134, name: 'Unimed Uba')
    Healthcare.create(id: 135, name: 'Unimed Uberaba Ltda.')
    Healthcare.create(id: 136, name: 'Unimed Uberlândia')
    Healthcare.create(id: 137, name: 'Unimed Vale Do Aço Cooperativa De Trabalho Médico')
    Healthcare.create(id: 138, name: 'Unimed Vale Do Carangola')
    Healthcare.create(id: 139, name: 'Unimed Vale Do Urucuia')
    Healthcare.create(id: 140, name: 'Unimed Varginha Cooperativa De Trabalho Médico')
    Healthcare.create(id: 141, name: 'Unimed Vertente Do Caparaó')
    Healthcare.create(id: 142, name: 'Valem')
    Healthcare.create(id: 143, name: 'Valem Benefícios')
    Healthcare.create(id: 144, name: 'Vivamed')
  end
end
